#!/bin/bash
QN_TARGET_EMAIL_PRIVATE=xxxx
QN_TARGET_EMAIL_WORK=xxxx
QN_FROM_EMAIL=xxxx
QN_SMTP_HOST=xxxx
QN_SMTP_USERNAME=xxxx
QN_SMTP_PASSWORD=xxxx
QN_SMTP_PORT=xxxx
GREEDY_FILE=/tmp/home-service.bolt
UPLOAD_TARGET=/Users/rlommers/projects/home/upload-target
USERNAME=
PASSWORD=
CLEANUP_DAYS=1
DEV=true
