---
services:
  home-service:
    tty: true
    init: true
    network_mode: "bridge"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - PORT=5000
