# playlist example: https://github.com/playlist-exchange/playlist-exchange/blob/main/.github/workflows/docker-image.yml

name: quick-note

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Run CI
      working-directory: ./frontend
      run: npm ci

    - name: Run build
      working-directory: ./frontend
      run: npm run build

    - name: (after) list files in dist
      run: |
        ls -lhr ./frontend/dist

    - uses: actions/upload-artifact@main
      with:
        name: dist-folder
        path: ./frontend/dist

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3

      - name: Build
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ./bin/quick-note ./backend/*.go

      - name: List files in ./bin directory
        run: |
          ls -lhr ./bin
      
      - uses: actions/upload-artifact@main
        with:
          name: compiled-binary
          path: ./bin/quick-note

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: build-binary
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@main
        with:
          name: compiled-binary
          path: ./bin/quick-note

      - uses: actions/download-artifact@main
        with:
          name: dist-folder
          path: ./bin/dist

      - name: List files in ./bin directory
        run: |
          ls -lhr ./bin

      - name: List files in current directory
        run: |
          pwd
          ls -lhr .

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build and push
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     push: true
      #     tags: rogierlommers/resume:latest