# playlist example: https://github.com/playlist-exchange/playlist-exchange/blob/main/.github/workflows/docker-image.yml

name: quick-note

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  # run-all-tests:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: list files
  #       run: |
  #         ls -lhr .
  #     - name: run development environment
  #       run: docker compose --env-file .env-dev -f docker-compose.yml -f docker-compose.dev.yml up --detach

  #     - name: run actual tests
  #       run: docker compose exec --no-TTY backend /app/scripts/tests-start.sh


  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      working-directory: ./frontend/
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
